version: '3.5'

services:
  store-app:
    container_name: storedatabase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.6-alpine